#let acronyms = (
  API: "Application Programming Interface",
  HTTP: "Hypertext Transfer Protocol",
  REST: "Representational State Transfer",
  URL: "Uniform Resource Locator",
  QM: "Qualitätsmanagement",
  QMS: "Qualitätsmanagementsystem",
  KMU: "Kleine und mittlere Unternehmen",
  ISO: "International Organization for Standardization",
  PA: "Process Approach",
  PDCA: "Plan-Do-Check-Act-Cycle",
  RBT: "Risk-Based Thinking",
  MP3: "MPEG-1 Audio Layer III",
  DE: "Deutschland",
  NL: "Niederlande",
  JP: "Japan",
)